### PR TITLE
Add UnwrapSource & UnwrapSink conditional TS types

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Comment by staltz** [comment]
I really like this utility, but I'd like to bikeshed the name a bit more, specially since it's a PR to core Callbag. If someone mentions "the source type", it's not sure if we're talking about "the `Source` type" or "the `SourceType`", so it's a bit ambiguous. I'm inclined to names like 

- `UnwrapSource` / `UnwrapSink`
- `SourceFactor` / `SinkFactor`
- `SourceItem` / `SinkItem`

Happy to hear more names and analysis on the naming.

cc @krawaller @franciscotln

**Comment by Andarist** [comment]
I agree the name is not the best - I've based this naming on `ReturnType` type, but it doesn't work as nicely here. 

I quite like Unwrap* as it's quite descriptive.

**Comment by staltz** [comment]
Let's go with Unwrap then, that was actually my first name that came to mind

**Comment by Andarist** [comment]
I've changed the names of those

**Comment by staltz** [comment]
Thanks!

**Pull request merged**
