### PR TITLE
Added isCallbag

### PR DESCRIPTION
**Pull request by kof**

### CODE REVIEW

**Comment by StreetStrider** [comment]
That is work for symbols:
```js
var mark = Symbol('isCallbag')
var cbg = (…) => { … } // creating callbag
cbg[mark] = true // marking as callbag
export function isCallbag (cbg) { return cbg && (mark in cbg) } // export predicate
```

**Comment by staltz** [comment]
Thanks @kof for the initiative.

I explained briefly on Twitter that my default approach would be to not merge this PR: https://twitter.com/andrestaltz/status/1004796824157327360?s=19

Because the goal of this spec is to minimize the consensus surface. In other words, this spec dictates the *absolute* minimum necessary for callbags to interoperate, and an isCallbag helper is not necessary.

That said, I'm still somewhat considering this PR, because one of the important usages is conversion, and so far we have conversion to/from observables, and this is only possible because of the Symbol.observable or the presence of a subscribe() function. However, if it were the case that an observable library would like to add conversion **from** a callbag, they might need an isCallbag in order to assist that.

Or maybe not. In RxJS for example there is bindNodeCallback that assumes the argument follows the Node.js style of callbacks, but makes use of no isNodeCallback dynamic typing. It's blind to its arguments actually.

So I'm divided about this PR, but so far defaulting to not merge. That said, I don't want to cause feelings of rejection, in fact I'd like to practice **supportive disagreement**, an idea I explain here: https://staltz.com/open-source-without-maintainers.html

The best way forward I think is to publish a fork. Make another standard, called Callbag++ or Callbag-typed or something like that, so that it's just publishing your PR as an independent work. The upside is that every Callbag-typed would be compatible with Callbag. And if community experimentation turns out to prove the extensions to be worthy, I can consider converging those ideas into this standard. What's important to realize is that there are no "official" callbags and "unofficial", everything is unofficial.

I hope I made sense :)

**Comment by staltz** [comment]
Another important thing to note is that callbags dont have to be written in the style I write them. In fact I recommend looking at the getting started guide where I show how to write callbags as JS classes. That's also one way of checking if an instance conforms to a type, in runtime.

**Comment by kof** [comment]
Sure. I had in mind one use case - when you support an observable as a data in any third party library. For e.g. redux-observable or jss observable rules. The beauty of observable is that I only need to subscribe and unsubscribe, I don't have to include any library like rx. Same is here, but I would need to be able to identify it.

**Pull request closed without merging**
