### PR TITLE
fix(types): make `Callbag<I, O>` covariant on `I` and contravariant on `O`

### LINKED ISSUE #52: Express variance in types
Putting it in the best type theoretical way I can muster, afaict, `Callbag<I, O>` is covariant on `I` and contravariant on `O`. (eg: `Source<"a" | "b">` should not be assignable to `Source<"a">`)

This isn't expressed in types (ie with current types [you can assign `Source<"a">` to `Source<"a" | "b">`][1] which shouldn't be allowed as it can cause runtime errors). This can be simply [fixed by using an interface][2] instead of a type alias.

Moreover, it would nice to use interfaces for `Source` and `Sink` as well as it would preserve names in error messages (right now error messages have `Callbag<never, T>` instead of `Source<T>` as type aliases [don't "create new names"][3])

If the changes are agreed upon I would love to send a PR! :)

EDIT: Also this would be a breaking change but only for those who already have error-prone code so imo no need for a major bump

[1]: https://www.typescriptlang.org/play?#code/IYIwyg9grgTgxgUwAQF4nErRAoA9LpAAQBcBnAWgQA8AHBOYymGCGbDaeZNUTL7PARIVqdBkxZteASwB2Aa1Towc+exUKlMhQIAm9ADbAYyAwmLLOiAFxIAwsAMGQwAOYAeWQgBuCGABokACJgIIA+bH04IxMkMwteKwRbBycXDy9fAODQpAAfYJBwyMNjU3NlVRTHZzd3EKDAzL8IqJjyhPAq+xr0+tyCoKKmnxaBYgBPOh60uoBJQIB5MKUAb2wkJAAKYlsABkDdatmPRcC5sIBKW28IaV0Abg3t3aQARkPbOeukW-unzY7WwAJkOAH5bMBZBMfn9HtgAL4PIA

[2]: https://www.typescriptlang.org/play?#code/IYIwyg9grgTgxgUwAQF4nErRAoA9LpAAQBcBnAWgQA8AHBOYymGCGbDaeZNUTL7PARIVqdBkxZteASwB2Aa1Towc+exUKlMhQIAm9ADbAYyAwmLLOiAFxIAwsAMGQwAOYAeWQgBuCGABokACJgIIA+bH04IxMkMwteKwRbBycXDy9fAODQpAAfYJBwyMNjU3NlVRTHZzd3EKDAzL8IqJjyhPAq+xr0+tyCoKKmnxaBOWI-ADNgRB60uoBJQIB5MKQAb2wkJAAKYlsABkDdaoWPFcDFsIBKW28IaV0Abm29g6QARhPbRbukB5PV47fa2ABMJwA-LZgLIAJ7-QEvbAAX2eQA

[3]: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN7LgLmQIjn2QF8AoUSWRFAIWQgA9IQATAZzU3LAE8AHFAGFkAXjQBuMmQD0M5AAUoAe0FQ+yAOQAjTcmCcAtgfagA5vpDI+graj3aArmGRQIAR0fA3rS9YEomljaePja+BKkmgB0svLICYlJySmpSQB6mcgAFEyCCJC+ImbKLqgAlGQIyiDsLiDKAEoQIHDGIGZ4waHhpGLc2JxCUnGKKmoaOnoGyMbsph1+NoG0Ds6uHl4+SwFa3QThkSQxo2ln58mZ6Tl5EAUQvvQlLrSV1bUubq3tnZjIIQdiCR+hhgXBOLQJEA

### PR DESCRIPTION
**Pull request by devanshj**
Closes #52

### CODE REVIEW

**Review by staltz — APPROVED** [review]

**Comment by staltz** [comment]
requesting more eyeballs: @Andarist @loreanvictor @jvanbruegge

**Comment by loreanvictor** [comment]
[looks ok](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDKAVAggJQ3AXjgAYBuAKFElgWVQBEttC4BGCq6eJFOAUQBy9FgCYO4LrV44+aPjgBqfegH0AzCzXjq3OnBlzFylQBYWJ7ZJ6oD8paoCsLB5ZrX9su8YBsLb691pTyNVAHYWUICpG2D7FQAOFnio91sQlQBOFgyKcgB6ACoC8jgCuCw4AGEAQwAbWoAjaoBzOAATRAA7aoBbAEsAYzraxDgoYAHgPoA3YABnOD7OsABXeAgAM2i4AEkSsurOtvau3sHh0bbgWpngKAWINdX1rfcAeX28ygkaJZg7jbVSZVYZNZoAHh2ABo4G8AHxwADeJTgAAoYAAudDYPAwtpYmr1MHgt4wnZwgCUWOmED6bQocDRmLgjGweKxOypcBpdIZTKxgnoeIA-FjDoguTz6eQAL7kfJFfblOBzR5QYEQTojdrXW73drVGDVT7fHSLTr-KCA4FoNWTcEYBGgf5HBaExotcGdYCzKAwx1IuUK4qlZVzJYAazgmu140mtwWbUNxtKX04vwtAKBqDQkYdTpALrabtBnowMO9voRiKD6cCObtwAAYkCYNBEPmWKiAHS96pQZpzLFYKBQaod8WUwgI20rdXAfO5OvbWfzt4oMdtqAOmE4BFEVEo3vd-uD4ej8fgyfkCnTtGqueTLGr+2O28EGeN8F73KFENlSpNTaPoYD6TU6miBYNmgOABk1I0lmAY53HGGAoD6H06hNZd3AAVU6AB3McwBfBd8GdYBXXQL9J33OByMLSji2ox8FyWDY7n0BFhX0OAsUrO4Uj0fCiOqEi8wYosFlzToIyvTpEDhOjJKY6S83Yzi9zgHicD4uABKgXIrgGWp+1QDYVk6AZQM1OAemqCNgBkuTHVRLlnMXchjNM8Y4AsqybM6OyHKcr9XPcsK4QobyzL8yzrLAoL7Mc91iWhWE4TcglSwhdL4V-L48jydA8wqAAfOAACEESGIKGlQNDgENJC4GqNTZPBLAETauACNQWq4AAKxWOZ4A4lqQPKBZDmOECHgjfIvjgzpRta1hnzzAByLBNro5KnK2na4AqzbKt2tyCsWkqOq62DDk6CB4HqhBxma44eo88qqu6hZJtqh6nvMlrKoWVEGjWOBEEeOy+maAALMbgGBhY22uuSvuqilFvIZbVuqEQNo67bNuOuBTt2lh9o84nMopS6ipY+dOtJ6q7s6AG4Gexq3ta6Sv1unqNigCAegQOHUFMmBLUh6GCMeWpjhjUYqAmeAsDmK7we4cW-OgHpOP6eH4DqVU4GAfoYAWEHsdx+A5nWxn7RpymQtI8FidJ8nafp4q3dugaude-53r51jmYq1mesm825qm3q4cGOHWt81EMYpUHTcmtoIHmM2LbRNO5hhHqVespCsaKnHNVWuYCcdhcPZOs69tdr8aYu8ggA).

**Review by loreanvictor — APPROVED** [review]

**Review by Andarist — APPROVED** [review]

**Review by jvanbruegge — APPROVED** [review]

**Comment by staltz** [comment]
awesome y'all!

**Comment by devanshj** [comment]
@staltz could you publish this!

**Comment by staltz** [comment]
@devanshj yes, we just need some formalities done first. can you send a PR to put your name in CopyrightWaivers.txt? Because this project is Public Domain (CC0).

**Comment by devanshj** [comment]
Yep done

**Comment by staltz** [comment]
1.4.0

**Pull request merged**
